name: pitch-in
services:
  pitch-in-mysql-service:
    platform: linux/amd64
    container_name: pitch-in-mysql-service
    image: mysql
    restart: always
    ports:
      - "33006:3306"
    volumes:
      - pitch-in-mysql-data:/var/lib/mysql
      # - ./db/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      start_period: 20s
      timeout: 5s
      retries: 5

volumes:
  pitch-in-mysql-data:
