name: pitch-in
services:
  pitch-in-mysql-service:
    platform: linux/amd64
    container_name: pitch-in-mysql-service
    image: mysql
    restart: always
    ports:
      - "33006:3306"
    volumes:
      - pitch-in-mysql-data:/var/lib/mysql
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      start_period: 20s
      timeout: 5s
      retries: 5
  pitch-in-api-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pitch-in-api-service
    depends_on:
      - pitch-in-mysql-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: on-failure

volumes:
  pitch-in-mysql-data:
